services:
  php-app: &php_default
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    user: "1000:1000"
    volumes:
      - .:/var/www
    networks:
      - backend

  server:
    image: nginx:alpine-slim
    container_name: server
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
    networks:
      - backend

  db:
    image: postgres:18rc1-alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - backend
    working_dir: /var/lib/postgresql
    volumes:
      - db_data:/var/lib/postgresql

networks:
  backend:
    driver: bridge

volumes:
  db_data:
